test:
  message: Hello from Gym Config Server



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gymdb
    username: root
    password: YOUR_MYSQL_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true